import type { EventItem } from './types';

/** TEMPORARY placeholder dataset — see api.ts for how this gets replaced. */
export const MOCK_EVENTS: EventItem[] = [
  {
    id: '1',
    title: 'Worship day',
    category: 'worship',
    description:
      'A day to worship the birth of Jesus Christ. Join us for candlelight prayer, hymns, and fellowship as we celebrate together.',
    dateLabel: 'Tire 24, 2019',
    isoDate: '2026-05-20',
    time: '12:00 PM - 8:00PM',
    location: 'AASTU',
    organizer: 'Gibi Gubae, AASTU',
    status: 'upcoming',
    highlights: ['Candlelight procession', 'Guest choir performance', 'Fellowship meal afterward', 'Open to all students'],
  },
  {
    id: '2',
    title: 'Bible Study Seminar',
    category: 'seminar',
    description:
      'An evening seminar exploring the Gospel of John, led by Dn. Abebe. Open discussion and Q&A follow the teaching.',
    dateLabel: 'Tir 12, 2019',
    isoDate: '2026-06-02',
    time: '2:00 PM - 4:30PM',
    location: 'AASTU',
    organizer: 'Gibi Gubae, AASTU',
    status: 'upcoming',
    highlights: ['Led by Dn. Abebe', 'Small-group discussion', 'Handouts provided'],
  },
  {
    id: '3',
    title: 'Orthodox Faith Foundation',
    category: 'course',
    description: 'A short course covering the foundations of Orthodox faith and practice for new members.',
    dateLabel: 'Tire 24, 2019',
    isoDate: '2026-05-28',
    time: '10:00 AM - 12:00PM',
    location: 'AASTU',
    organizer: 'Gibi Gubae, AASTU',
    status: 'upcoming',
    highlights: ['6-week course', 'Weekly reading assignments'],
  },
  {
    id: '4',
    title: 'Annual Leadership Conference',
    category: 'conference',
    description:
      'Gibi Gubae leaders from across the region gather for a day of training, worship, and strategic planning.',
    dateLabel: 'Meskerem 3, 2018',
    isoDate: '2025-09-13',
    time: '9:00 AM - 5:00PM',
    location: 'AASTU',
    organizer: 'Gibi Gubae, AASTU',
    status: 'past',
    highlights: ['Keynote sessions', 'Leadership workshops', 'Regional networking'],
  },
  {
    id: '5',
    title: 'Trip to Seminesh Kidane Mihret',
    category: 'worship',
    description: 'A day trip to Seminesh Kidane Mihret and Kukiyelesh Mariam Monastery for prayer and reflection.',
    dateLabel: 'March 21, 2025',
    isoDate: '2025-03-21',
    time: '6:00 AM - 6:00PM',
    location: 'Off-campus',
    organizer: 'Gibi Gubae, AASTU',
    status: 'past',
    highlights: ['Bus transport provided', 'Guided monastery tour', 'Packed lunch included'],
  },
  {
    id: '6',
    title: 'General Assembly',
    category: 'conference',
    description: 'Quarterly general assembly covering schedule updates, elections, and member announcements.',
    dateLabel: 'Oct 27, 2018',
    isoDate: '2025-10-27',
    time: '4:00 PM - 6:00PM',
    location: 'AASTU',
    organizer: 'Gibi Gubae, AASTU',
    status: 'featured',
    highlights: ['Schedule updates', 'Committee elections'],
  },
];
